### ISSUE TITLE
Integration with Ionic - ionic universal (support)

### ISSUE THREAD

**Issue by Gorniv** [Angular-RU/angular-universal-starter#1]
Ветка Ionic
Проблемы:
- решить проблему c Config (https://github.com/Angular-RU/angular-universal-starter/issues/2)
- решить проблему с работой после сборки( смотрите клик по меню)

**Comment by splincode** [comment]
А каким боком Ionic связан с серверный рендерингом? почему не создать новый репозиторий?

**Comment by Gorniv** [comment]
потому что ionic в принципе можно собрать под universal (его web представление). Вообще не смотря на то что ionic можно использовать не только для mobile но и для создания сайта информации по этой теме не много. Я думал на отдельным репозиторием, но количество материала пока не достаточно.
В репозитории несколько веток - так как это позволяет достаточно легко находить разницу между использованием разных пакетов, упрощает поддержку и ускоряет сборку. ( репозиторий до разделения собирался 20 минут)

**Comment by DominikTrenz** [comment]
global['Node'] = domino.impl.Node; 

fixes this Problem:
ERROR ReferenceError: Node is not defined

**Comment by DominikTrenz** [comment]
@Gorniv Maybe it is possible to build ssr with the new ionic version that supports angular router:
https://github.com/ionic-team/ionic/tree/core/packages/demos/ng-nav-routing

**Comment by Gorniv** [comment]
@DominikTrenz thank you. I fix `ERROR ReferenceError: Node is not defined` but other problems are actual.
