### ISSUE TITLE
Error in IE11 (looks like some polyfill(s) absent): 'not supported by object'

### ISSUE THREAD

**Issue by MichaelSemchenko** [Angular-RU/angular-universal-starter#13]
Reproducing:
1. Uncomment all common polyfill's imports in polyfills.ts
2. Run app in IE11.

Error screenshot: 
![ie11_error](https://user-images.githubusercontent.com/8709333/35081209-bf104726-fc23-11e7-95a6-ab7e547fabf8.png)

**Comment by Gorniv** [comment]
ппц, пока не понял что он хочет. Причем фишка, в других двух проектах(приватных и более больших) все ок.
