### ISSUE TITLE
Redirect from an external URL

### ISSUE THREAD

**Issue by marcocoelho** [Angular-RU/angular-universal-starter#143]
Guys, I need a help.
I need to do a Universal Angular redirect to an external URL.

When returning the API from an id that does not exist I need to send to an external URL of my app.

As it runs on the server, I can't use the default redirect.
Has anyone of you ever been through this? How to make? Can you help me please?

**Comment by Gorniv** [comment]
Are you try https://github.com/Angular-RU/angular-universal-starter/blob/master/server.ts#L75 ?
