### ISSUE TITLE
'format:check command not working

### ISSUE THREAD

**Issue by biijoy508** [Angular-RU/angular-universal-starter#160]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\MKHN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'format:check' ]
2 info using npm@6.9.0
3 info using node@v8.9.1
4 verbose run-script [ 'preformat:check', 'format:check', 'postformat:check' ]
5 info lifecycle farmen-gui@0.0.0~preformat:check: farmen-gui@0.0.0
6 info lifecycle farmen-gui@0.0.0~format:check: farmen-gui@0.0.0
7 verbose lifecycle farmen-gui@0.0.0~format:check: unsafe-perm in lifecycle true
8 verbose lifecycle farmen-gui@0.0.0~format:check: PATH: C:\Users\MKHN\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\farmen\farmen-gui\node_modules\.bin;C:\opt\python\Scripts;C:\opt\python;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\opt\apache-maven-3.6.0\bin;C:\Program Files\PuTTY\;C:\Program Files\Oracle\Berkeley DB 12cR1 6.2.32\bin;C:\opt\oracle\instantclient_11_2;C:\ORACLE\Product\11.2\client_1;C:\opt\jdk1.8.0_161-64\bin;C:\opt\jboss-eap-6.2\bin;C:\opt\jdk1.8.0_161-64\jre\bin;C:\Program Files\PostgreSQL\pg95\bin;C:\Program Files\PostgreSQL\pg95\lib;C:\opt\oracle EAP 6.2\ojdbc6.jar;C:\opt\apache-tomcat-8.5.31\bin;C:\Program Files (x86)\cvsnt\;C:\opt\apache-ant-1.9.11\bin\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\MKHN\AppData\Local\Microsoft\WindowsApps;C:\Users\MKHN\AppData\Roaming\npm;C:\opt\python;C:\opt\jdk1.7.0_55-64\jre;C:\opt\jdk1.7.0_55-64;C:\opt\oracle\instantclient_11_2;C:\Program Files\Microsoft VS Code\bin;C:\opt\python\Scripts;C:\opt\flyway;C:\Users\MKHN\AppData\Local\Programs\Microsoft VS Code\bin;
9 verbose lifecycle farmen-gui@0.0.0~format:check: CWD: D:\farmen\farmen-gui
10 silly lifecycle farmen-gui@0.0.0~format:check: Args: [ '/d /s /c',
10 silly lifecycle   'prettier --write --config ./.prettierrc --list-different "src/{app,environments,styles}/**/*{.ts,.json,.scss}"' ]
11 silly lifecycle farmen-gui@0.0.0~format:check: Returned: code: 2  signal: null
12 info lifecycle farmen-gui@0.0.0~format:check: Failed to exec format:check script
13 verbose stack Error: farmen-gui@0.0.0 format:check: `prettier --write --config ./.prettierrc --list-different "src/{app,environments,styles}/**/*{.ts,.json,.scss}"`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\MKHN\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\MKHN\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid farmen-gui@0.0.0
15 verbose cwd D:\farmen\farmen-gui
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MKHN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "format:check"
18 verbose node v8.9.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error farmen-gui@0.0.0 format:check: `prettier --write --config ./.prettierrc --list-different "src/{app,environments,styles}/**/*{.ts,.json,.scss}"`
22 error Exit status 2
23 error Failed at the farmen-gui@0.0.0 format:check script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by vadjs** [comment]
Looks like this is not problem of this project. Trace log shown no any error related to this project/npm script.
Looks like this is a problem of tool that you are using ru run this project. I have no idea what tool you are using but it doens't work.
