### ISSUE TITLE
Question. InlineStyleComponent

### ISSUE THREAD

**Issue by bl9l** [Angular-RU/angular-universal-starter#169]
Hi.
Why do you use InlineStyleComponent instead of the standard Angular way with styles.scss?

**Comment by vadjs** [comment]
Good question. I hope @Gorniv knows the answer.

**Comment by Gorniv** [comment]
Inline style css load:
![inline (1)](https://user-images.githubusercontent.com/963316/67315884-23c67000-f510-11e9-855c-8512c505cf08.png)

standard Angular way:
![standart (1)](https://user-images.githubusercontent.com/963316/67315892-26c16080-f510-11e9-9965-23aba57e666e.png)
I think, that inline style is better for user experience. But inline style may be bad for rendering time.

**Comment by bl9l** [comment]
Thanks
