### ISSUE TITLE
window is not defined  with DOMINO - Angular 9

### ISSUE THREAD

**Issue by anishchcenko** [Angular-RU/angular-universal-starter#235]
HI ! 
we use your sample, but after update 3rd party library and angular to last versions , i have
ReferenceError: window is not defined when i trying to start server.

we use domino as in your example and nothing has changed in server.ts after update to Angular 9.
but have this issue (

 server.ts

`import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import {enableProdMode} from '@angular/core';
import { readFileSync } from 'fs';
import { renderModuleFactory } from '@angular/platform-server';
import cookieParser from 'cookie-parser';

import * as express from 'express';
import {join} from 'path';
import { InjectionToken } from '@angular/core';

const http = require('http');
var compression = require('compression')

enableProdMode();

// Express server
const app = express();
const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist');

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const {AppServerModuleNgFactory, LAZY_MODULE_MAP} = require('./dist/server/main');

// Express Engine
// import { ngExpressEngine } from '@nguniversal/express-engine';
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
import { NgxRequest, NgxResponse } from '@gorniv/ngx-universal';
// Import module map for lazy loading
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)

// angular/universal#830

const domino = require('domino');
const path = require('path');
const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();
const win = domino.createWindow(template);
// mock
global['window'] = win;
global["navigator"] = win.navigator;
global['document'] = win.document;

app.use(cookieParser());
app.use(compression())

// // ALl regular routes use the Universal engine
const cacheTime = 864000007; // 7 days
app.get('.*', express.static(join(DIST_FOLDER, 'browser'), { maxAge: cacheTime }));

app.engine('html', (_, options, callback) => {
const host = options.req.headers.host;
const param = options.req.query;
const hl = options.req.query['hl'];
const http = options.req.headers['x-forwarded-proto'] === undefined ? 'https' : options.req.headers['x-forwarded-proto'];
const ip = options.req.headers['x-forwarded-for'] || options.req.connection.remoteAddress;
renderModuleFactory(AppServerModuleNgFactory, {
url: options.req.url,
extraProviders: [
provideModuleMap(LAZY_MODULE_MAP),
{
provide: 'REQUEST',
// useValue: options.req
useFactory: () => options.req,
deps: []
},
{
provide: 'RESPONSE',
useValue: options.req.res
},
{
provide: NgxRequest,
useValue: options.req,
},
{
provide: NgxResponse,
useValue: options.req.res,
},
{
provide:'serverUrl',
useValue: (${http}://${host})
},
{
provide: 'IP',
useValue: ip
},
{
provide: "HL",
useValue: hl
}
]
}).then(html => {
callback(null, html);
});
});

// All regular routes use the Universal engine
app.get('*', (req, res) => {
global['navigator'] = req['headers']['user-agent'];
const http = req.headers['x-forwarded-proto'] === undefined ? 'http' : req.headers['x-forwarded-proto'];
res.render(
'index',
{
req: req,
res: res,
preboot: true,
providers: [
{
provide: REQUEST, useValue: (req)
},
{
provide: RESPONSE, useValue: (res)
},
/// for cookie
{
provide: NgxRequest,
useValue: req,
},
{
provide: NgxResponse,
useValue: res,
}
]
},
);
});

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, 'browser'));

app.use((err, request, response, next) => {
// console.log( 'ERROR CODE')
// response.status(500).send(‘Something broke!’)
})

// Start up the Node server
app.listen(PORT, () => {
console.log(Node Express server listening on http://localhost:${PORT});
});`

`  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^9.0.5",
    "@angular/cdk": "^9.1.1",
    "@angular/common": "^9.0.5",
    "@angular/compiler": "^9.0.5",
    "@angular/core": "^9.0.5",
    "@angular/elements": "^9.0.5",
    "@angular/forms": "^9.0.5",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "^9.0.5",
    "@angular/platform-browser-dynamic": "^9.0.5",
    "@angular/platform-server": "^9.0.5",
    "@angular/router": "^9.0.5",
    "@angular/service-worker": "^9.0.5",
    "@gorniv/ngx-universal": "^2.2.2",
    "@nguniversal/express-engine": "^9.0.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.2.6",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/express-serve-static-core": "^4.17.2",
    "angular-calendar": "^0.26.3",
    "angular-cd-timer": "^1.0.0",
    "angular-draggable-droppable": "^4.3.10",
    "angular2-toaster": "^8.0.0",
    "chart.js": "^2.9.3",
    "compression": "^1.7.4",
    "concat": "^1.0.3",
    "cookie-parser": "^1.4.3",
    "core-js": "^3.6.4",
    "cropperjs": "^1.5.6",
    "date-fns": "^1.30.1",
    "document-register-element": "^1.14.3",
    "domino": "^2.1.4",
    "moment": "^2.24.0",
    "ng-click-outside": "^6.0.0",
    "ng-navigator-share": "^1.0.1",
    "ng-recaptcha": "^5.0.0",
    "ng2-adsense": "^7.0.0",
    "ng2-charts": "^2.3.0",
    "ngx-clipboard": "^13.0.0",
    "ngx-infinite-scroll": "^8.0.1",
    "ngx-translate-multi-http-loader": "^3.0.0",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "xlsx": "^0.15.5",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.5",
    "@angular-devkit/core": "^9.0.5",
    "@angular/cli": "^9.0.5",
    "@angular/compiler-cli": "^9.0.5",
    "@angular/language-service": "^9.0.5",
    "@types/jasmine": "^3.4.0",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^13.7.7",
    "@typescript-eslint/eslint-plugin": "^2.15.0",
    "@typescript-eslint/parser": "^2.15.0",
    "body-parser": "^1.19.0",
    "codelyzer": "^5.1.2",
    "eslint": "^6.8.0",
    "express": "^4.17.1",
    "http": "0.0.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.3.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "localstorage-polyfill": "^1.0.1",
    "morgan": "^1.9.1",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.6",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.2",
    "tslint": "^5.20.0",
    "typescript": "^3.6.5",
    "webpack-cli": "^3.3.11",
    "winston": "^3.1.0"
  }`

**Comment by brunano21** [comment]
@anishchcenko I see you closed the issue, but I'm facing the same issue - do you recollect what was your issue?
