### ISSUE TITLE
Есть идеи по развитию серверной части с Nest.js?

### ISSUE THREAD

**Issue by splincode** [Angular-RU/angular-universal-starter#3]
Интересно было бы увидеть реализацию не на Express.js, а на модульном фреймворке Nest.js. 
Посмотреть на: проблемы, идеи, реализации, костыли, патчи (все что было необходимо для интеграции).

**Comment by vadjs** [comment]
Смысл использования Express - максимальное упрощение настройки серверной части.
В принципе, от Express в перспективе вообще можно отказаться и переписать необходимый функционал на чистой Node.js, но данная процедура на данный момент не оправдана в силу своей трудоёмкости и малого конечного профита(особенно, в сравнении с текущими проблемами).

Идея переписать на ином фреймворке, на мой взгляд, слишком сомнительна.

**Comment by FriOne** [comment]
@vadjs Вообще-то nestjs обертка над express. @splincode вохможно после angular конфы по nest, его создатель что-нибудь придумает. Сейчас, наверно, можно таким https://docs.nestjs.com/faq/express-instance образом добавить к приложению ngEspressEngine.

**Comment by vadjs** [comment]
@FriOne Если Nest.js - обёртка над Express, то смысл переписывать universal под него вооще непонятен. Ещё один слой для и без того простого кода.

**Comment by splincode** [comment]
Я не говорил, что нам нужно переписывать что-либо. Если мы используем Node.js как сервер бизнес-логики (BL), вместо Java, Asp.net или чего-либо, то для лучшей модульности и разработки этой самой BL хотелось бы видеть что-то приличнее, чем то, что сейчас описывается в server.ts.

Или проще поднять еще одно сетевое приложение (которое будет на Nest) и тогда они будут общаться?

**Comment by FriOne** [comment]
@vadjs не universal под него. Если автор nest захочет привлечь побольше людей, сам напишет интеграцию. Затея не странная, любую тулзу оценивают из простоты вхождения и использования.

**Comment by Gorniv** [comment]
вообще фронт на universal  может легко общаться с любым бэком( у меня бэк на .net core),  а различные реализации universal (.net, nodjs) нужны только для того, чтобы middleware был на привычном языке разработчика.
Не вижу необходимости реализации nestjs.  Для желающих смотрите https://github.com/angular/universal/blob/master/modules/express-engine/src/main.ts
