### ISSUE TITLE
Google Analytics enhancement ?

### ISSUE THREAD

**Issue by pier7529** [Angular-RU/angular-universal-starter#32]
Hi,
Great job done with this starter. Do you plan also to integrate "Google Analytics" vs SSR into it ?

**Comment by Gorniv** [comment]
What is a problem with "Google Analytics"?

**Comment by pier7529** [comment]
Do your starter in SSR Server Side Rendering mode able to trigger "Google Analytics" ?

**Comment by Gorniv** [comment]
you can add script GA on index.html

**Comment by Gorniv** [comment]
You can try https://github.com/angulartics/angulartics2 for more advanced actions.

**Comment by pier7529** [comment]
OK I will check. I already have GA on index.html and since I've migrated to SSR, it's no more working.
So, no contraindications with SSR and GA. Thanks
