### ISSUE TITLE
How to use this (in my opinion)

### ISSUE THREAD

**Issue by JusteG** [Angular-RU/angular-universal-starter#35]
git clone => npm i => npm run start =

ERROR in src/app/shared/layouts/toolbar/toolbar.component.ts(3,10): error TS2305: Module '"E:/tmp/angular-universal-starter-master/src/app/shared/translates/index"' has no exported member 'TranslatesService'.
src/app/shared/layouts/toolbar/toolbar.component.ts(3,29): error TS2305: Module '"E:/tmp/angular-universal-starter-master/src/app/shared/translates/index"' has no exported member 'ITranslatesLanguage'.
src/app/shared/translates/index.ts(1,40): error TS2307: Cannot find module './translates-server.module'.

[Hmmm... Nice starter, i like it!]
cd .. => rm -rf an[Tab][Enter]

**Comment by Gorniv** [comment]
```bash
Igors-MBP:angular-universal-starter gorniv$ npm start

> universal-demo@0.0.0 start /Users/gorniv/GitHub/Angular-RU/angular-universal-starter
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-21T16:25:45.050Z
Hash: 2996484897c4b41f323a
Time: 9539ms
chunk {home.module} home.module.chunk.js () 12.5 kB  [rendered]
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 119 kB [initial] [rendered]
chunk {mock-server-browser.module} mock-server-browser.module.chunk.js () 38.5 kB  [rendered]
chunk {not-found.module} not-found.module.chunk.js () 16.3 kB  [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 611 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 66.6 kB [initial] [rendered]
chunk {transfer-back.module} transfer-back.module.chunk.js () 16 kB  [rendered]
chunk {vendor} vendor.bundle.js (vendor) 10.2 MB [initial] [rendered]

webpack: Compiled successfully.
```
https://semaphoreci.com/angularru/angular-universal-starter/branches/master

**Comment by JusteG** [comment]
I tried one more time and it works. Idk why. But i am sorry.
