### ISSUE TITLE
Module not found: Error: Can't resolve '.' 

### ISSUE THREAD

**Issue by hesampour** [Angular-RU/angular-universal-starter#42]
I get the following error when building the project. 

ERROR in ./dist-server/main.54d14887e93771cd2a49.bundle.js
Module not found: Error: Can't resolve '.' in 'C:\Users\Loqman\OneDrive\programming\with universal starter\dist-server'
 @ ./dist-server/main.54d14887e93771cd2a49.bundle.js 1:614175-614187
 @ ./dist-server ^\.\/main\..*\.bundle$
 @ ./server.ts

**Comment by Gorniv** [comment]
Hello. Is it master branch? Try a reinstall and rebuild the app. 
What npm command do you use?

**Comment by Gorniv** [comment]
try `npm run ssr`
How do you run server?

**Comment by hesampour** [comment]
still problem exist. I think the problem is with the server.ts file. because when I open the ./dist-sever/main...
there is 
function(n,l){n.exports=require(".")} 

this is the source of the error.

**Comment by splincode** [comment]
@hesampour Can you provide more detailed inspection?

**Comment by hesampour** [comment]
the problem is with one of the modules but I don't know which module has problem. I removed one part of my project from universal and compile that part separately. But I don't know what is the problem. If I could make the whole project universal I would do that. But for know because of the above error I cant

**Comment by roydekleijn** [comment]
is it resolved? and how?

**Comment by ohabash** [comment]
I think this means that main.js is dependent on a file that is not built yet. If running it twice in a row (without deleting dist) then its a good sign that is the problem... Im currently trying to solve this but open to ideas. I think requires instead of imports may be the problem.
