### ISSUE TITLE
Not able to access window.screen and localStorage

### ISSUE THREAD

**Issue by ishan123456789** [Angular-RU/angular-universal-starter#50]
I'm getting undefined when trying to get height of screen while running ssr and localStorage is also not available.I'm trying to implement your app into my by copying every file and the required parts, might be that I'm missing something important.

**Comment by vadjs** [comment]
Because you have no window.screen and localStorage on server.

**Comment by ishan123456789** [comment]
Any option available to have present code work on server as well. As my ssr code is rendered same way as browser code due to this error.
When I do `ctrl + u` I only see two scripts and `app-root` in both browser and server

**Comment by Gorniv** [comment]
Because you have no window.screen and localStorage on server.
use cookies for cross save server-browser.
