### ISSUE TITLE
Auto restart and rebuild angular universal on save

### ISSUE THREAD

**Issue by samialmorshedi** [Angular-RU/angular-universal-starter#51]
I turned my application to angular universal. It's great but I have a problem with developing mode. I need to see my editing result real-time. I need to restart my app on each atrl+s (save) like `build --watch` and `nodmeon`.

My server is Eexpressjs and I'm using the command  `"npm run build:ssr"` after each edit. It takes lots of time!!
How can I do that?

**Comment by vadjs** [comment]
#47 is a reason why watch mode not working with universal right now. 
We need to wait new stable version of **angular/devkit**.
