### ISSUE TITLE
Dynamic meta injection inside constructor

### ISSUE THREAD

**Issue by Luarb** [Angular-RU/angular-universal-starter#61]
I was wondering if there could be a way to inject meta tags and title 
for any component in their respective constructor.

I have a Search Result component which updates its meta and title
on each different search, but I cant find a way to inject the meta and title dynamically.

**Comment by ishan123456789** [comment]
There's a module named ngx-meta and other but I'm still not able to implement a method so that crawlers pickup the meta tags

**Comment by Gorniv** [comment]
like https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/home/home.component.ts#L29
