### ISSUE TITLE
Firebase hosting

### ISSUE THREAD

**Issue by chenlitchian** [Angular-RU/angular-universal-starter#73]
Need to host the application using firebase hosting provider, how to setup in firebase hosting for this starter?

**Comment by omnecon** [comment]
As I also wanted to use firebase hosting (or to host the files on a static webserver), I took following approach:

- Added routes to: static.paths.ts
- called: npm run build:prerender
- copied files from static/* and dist-server/* into dist
- configured firebase-hosting for public folder "dist"  ...and called firebase deploy, which did the trick.


To get prerendering to work I had to ad exisSync(syncpath) in prerender.ts:

 if (!existsSync(syncpath)) {
        mkdirSync(syncpath);
      } 

Please let me know if there is a better approach to get static hosting of the project to work. thx!

**Comment by Gorniv** [comment]
Serverless and function, not good hosting, because it has long time start. Use [prerender](https://github.com/Angular-RU/angular-universal-starter/blob/master/prerender.ts) and static hosting
Or you can try https://fireship.io/lessons/angular-universal-firebase/

**Comment by kunalkakkad** [comment]
Does hosting on firebase we need to use prerender only? Can't we use SSR?
And many of my application's URLs are dynamic like "domain.com/user/{id}". So how do i define the same in static.path.ts?

Kindly help me out as I am pretty much confused as need to make the deploy ASAP.

Thanks,
Kunal Kakkad
