### ISSUE TITLE
publish to server

### ISSUE THREAD

**Issue by hofa77** [Angular-RU/angular-universal-starter#75]
Hi

How can I publish this angular universal to a windows server  ?
thank you

**Comment by Gorniv** [comment]
copy `server.js`
copy `dist`
copy `static` (if use)
copy `dist-server`
`node server.js`

**Comment by hofa77** [comment]
Thnaks
but it's listening on his url => listening on http://localhost:4000!

how can I change it to listen to a domain ?

**Comment by vadjs** [comment]
@hofa77 https://stackoverflow.com/questions/5489956/how-could-others-on-a-local-network-access-my-nodejs-app-while-its-running-on
