### ISSUE TITLE
Problem with production mode. error from terser

### ISSUE THREAD

**Issue by kuzne** [Angular-RU/angular-universal-starter#76]
when in `webpack.config` I set up production mode and run "`build: prerender`", an error is thrown out
```
ERROR in prerender.js from Terser
Unexpected token: punc (.) [Prerender.js: 91750,10]

ERROR in server.js from Terser
Unexpected token: punc (.) [Server.js: 153477,10]
```
installing `"terser": "3.14.1"` does not help.

**Comment by Gorniv** [comment]
`webpack.config` must be at `mode: development`
