### ISSUE TITLE
AWS Lamda Serverless

### ISSUE THREAD

**Issue by sgomez84** [Angular-RU/angular-universal-starter#77]
Has anyone tried to deploy this using AWS lamda using serverless?
Some lead will be much appreciated.

**Comment by Gorniv** [comment]
Serverless and function, not good hosting, because it has long time start. Use [prerender](https://github.com/Angular-RU/angular-universal-starter/blob/master/prerender.ts) and static hosting

**Comment by sgomez84** [comment]
@Gorniv Yes, I agree. I used the `renderModuleFactory` to pre-render and it works like a charm; lighthouse report went through the rood.
