### ISSUE TITLE
node prerender.js   Chart is not defined

### ISSUE THREAD

**Issue by tuanuvt001** [Angular-RU/angular-universal-starter#84]
I use Ng2-chart and  build ssr return : 
 Chart is not defined
    at eval (webpack:///./node_modules/ng2-charts/fesm5/ng2-charts.js?:1041:15)

How I fix this?

**Comment by Gorniv** [comment]
Hi.
You can try `global['CSS'] = null;` like [CSS](https://github.com/Angular-RU/angular-universal-starter/blob/dd2c6ba51cbb835c5cc94429953e4a9c5dd6af67/server.ts#L34)
or mock like [mock-server-browser](https://github.com/Angular-RU/angular-universal-starter/tree/master/src/app/mock-server-browser)

**Comment by tuanuvt001** [comment]
> Hi.
> You can try `global['CSS'] = null;` like [CSS](https://github.com/Angular-RU/angular-universal-starter/blob/dd2c6ba51cbb835c5cc94429953e4a9c5dd6af67/server.ts#L34)
> or mock like [mock-server-browser](https://github.com/Angular-RU/angular-universal-starter/tree/master/src/app/mock-server-browser)

Thanks! I did that.
