### ISSUE TITLE
Prerender deploy

### ISSUE THREAD

**Issue by call-me-adas** [Angular-RU/angular-universal-starter#86]
How can i deploy website using yarn build:prerender ?

**Comment by Gorniv** [comment]
build all your path of the app. 
Then you need to deploy like the static site(nginx)

**Comment by gregor-srdic** [comment]
Can you please be more specific

1. npm run build:universal
2. npm run build:prerender
3. **which folders need to be copied to static web server**? (e.g. I see  static, dist, and dist-server beeing generated ...) Also, any specific rule where should I put them?
