### ISSUE TITLE
using TransferHttp / TransferState in APP_INITIALIZER

### ISSUE THREAD

**Issue by MichaelSemchenko** [Angular-RU/angular-universal-starter#9]
When you try to use TransferHttp or TransferState in the service, provided by APP_INITIALIZER, all requests that uses TransferHttp in app executes twice (on the client and on the server).

For reproducing:
1. clone https://github.com/MichaelSemchenko/angular-universal-starter
2. npm run ssr
3. go to the /back rout and refresh page

If we use HttpClient instead TransferHttp in app-load.service.ts, all requests in transfer-back.component.ts works fine and not executes twice, but (obviously) data is not transfered via transferState to the client.

Expected: 
TransferHttp in APP_INITIALIZER prodided service doesn't brake in caching via TransferState, requests executes once on the server, data passed via TranferState

**Comment by Gorniv** [comment]
I can say only: don't use TransferState in APP_INITIALIZER because it has broken all TransferState.  Transfer state in APP_INITIALIZER  always init state like {} and after work broke state from a server( rewrite) You need wite issue in angular.
