### ISSUE TITLE
Error with dynamic import and lazy loading

### ISSUE THREAD

**Issue by devbenzy** [Angular-RU/angular-universal-starter#92]
Hi,
I need to load some modules in the following way but its giving me an error "Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'." can you check and share a working sample ?

{
    path: '',
    component: WrapperComponent,
    canActivateChild: [MetaGuard],
    children: [{
      path: 'home', loadChildren: ()  = {
       //I need to write some logic here to decide which module it should load, for now i am simply returning the below.
        return import('./home/home.module').then(mod => mod.HomeModule)
      }
    
    },

**Comment by Gorniv** [comment]
`return import('./home/home.module').then(mod => mod.HomeModule)`
this syntactic only for ivy or JIT
use: `        loadChildren: './mock-server-browser/mock-server-browser.module#MockServerBrowserModule',`
