### ISSUE TITLE
buildOptimizer problem

### ISSUE THREAD

**Issue by abdurrahmanarikan** [Angular-RU/angular-universal-starter#93]
Hi
There is an intermittent problem with buildOptimizer config on angular.json file. When I make it true, and push my repo to aws by prerendering, it generates a url. The web site works for me but for some developers, it does not. In addition, I clean all my cache and hard reset my browser, it still works for me but for some others doesn't. I really don't know how to figure out what is the problem. Can you help ?

**Comment by vadjs** [comment]
We can't help you until you provide error logs.
